run:
  seed: 12345
  figsize: [6.6, 4.2]
  dpi: 140

  plane:
    Nx: 40
    Ny: 40
    extent: 1.0

  sphere:
    R: 1.0
    Nu: 64
    Nv: 32

  saddle:
    Nx: 40
    Ny: 40
    extent: 0.6
    alpha: 0.6

  sphere_refine:
    - {Nu: 16, Nv: 8}
    - {Nu: 32, Nv: 16}
    - {Nu: 64, Nv: 32}
    - {Nu: 128, Nv: 64}
